### ISSUE TITLE
The "body" attibute of the mailbox item is ALWAYS null

### ISSUE THREAD

**Issue by merlinbeedell** [OfficeDev/Outlook-Add-in-LinkRevealer#9]
SCRIPT5007: Unable to get property 'getAsync' of undefined or null reference 
Home.js, line 15 character 13

```
        Office.context.mailbox.item.body.getAsync("html", processHtmlBody);
```

I have not been able to get this to work on Exchange 2013 with the latest service packs applied.
I think the "body" attribute is depreciated in all places except the documentation.
I think that I need to do an Async call back to the server passing the user token and using an EWS call to get the full email direct from Exchange??  Is that really true?  If so, is there an example of this?

**Comment by merlinbeedell** [comment]
Correction - it shows the links in Outlook client - but not in OWA.

**Comment by AndrewJByrne** [comment]
Hi @merlinbeedell 

Thanks for getting in touch and sorry to hear you are having issues. Is your Exchange instance an on-premise instance? If so, I wonder if you are being hit by the fact that OWA on Exchange 2013 on-premise does not support the 1.3 requirements set (see table at the end of this [document](https://dev.outlook.com/reference/add-ins/tutorial-api-requirement-sets.html)) If it is Exchange 2013 on-prem, it doesn't support the [getAsync on the body object since that requires 1.3](https://dev.outlook.com/reference/add-ins/Body.html#getAsync) ?

**Comment by merlinbeedell** [comment]
Yes - it is an on-premise Exchange.  APP dev is extraordinarily difficult when there are so many caveats that are not very clear.  All to often ending up with the dreaded 'App Error' message.
So all i would like to know...
 Is there a supported way in ALL Exchange 2013 variations and clients that could perform this 'Link Revealer' feature? (which is _exactly_ the thing I need to achieve).

**Comment by AndrewJByrne** [comment]
Hi #merlinbeedell            

Unfortunately there isn’t a way to do this using the body.getAsync() call that will work across all clients that are connecting to your Exchange 2013 on-prem backend because of these requirement set differences.  I don’t have any info on a roadmap for OWA on Exchange 2013 On-Premise, or Mac Outlook 2016 supporting requirement set 1.3.  I see two options:

A)	Check whether the specific method is supported. While there is a more robust way to check this for Word and Excel, the only way to check in Outlook currently is to do the following:
if (Office.context.mailbox.item.body.getAsync()) {
  // Make the call
}
B)	Use makeEwsRequestAsync  instead. The limitation here is that you need to add ReadWritemailbox permissions to use this method.  Here’s a sample that shows it in use: https://github.com/OfficeDev/Outlook-Add-in-JavaScript-MakeEWSRequest
